### Site metadata ###

title: Gist Viewer
description: A list of all of my gists

email:
twitter_username:
github_username: MichaelCurrin

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/gist-viewer"

theme: minima

exclude:
  - LICENSE
  - README.md
  - Makefile

  # In Jekyll 4, these are always excluded, so you never have to add them to your list.
  # But in Jekyll 3, these are needed:
  - Gemfile
  - Gemfile.lock
  - vendor/
